export let localizedString = {
  En:{
    Menubar: {
      Cal: "Calendar",
      Eq: "My team",
      Res: "Reservation",
      Voy: "My trips",
      Par: "Parameters",
    },
    LoginButton: {
      co: 'Connect',
      disco: 'Disconnect',
    },
    Register: {
      bvn: 'Welcome to Ovalion !',
      addr: 'Email',
      mdp: 'Password',
      city: 'City',
      reg: 'Register',
    },
    Login: {
      log: 'Connect',
      addr: 'Email',
      mdp: 'Password',
    },
    Calendar:{},
    Parametres: {
      title: 'Choose your team',
      follow: 'You are following',
      followAll: 'Follow all teams',
      allteams: 'all teams',
      noFollow: 'You are not following any team',
    },
    MonEquipe: {
      rank: 'Ranking',
      history: 'Matches history',
      equipe: 'Team',
      noteam: 'You must choose a team to follow before accessing this page',
      home: 'HOME',
      away: 'AWAY',
    },
    MatchHistoryItem: {
      localeIdentifier: 'En',
    },
    Reserver: {
      choseMatch: 'Choose a match',
      choseTrip: 'Choose a trip',
      payment: 'Payment',
      home: 'HOME',
      away: 'AWAY',
    },
    MatchBookingItem: {
      localeIdentifier: 'En',
      hometeam: 'Home Team',
      awayteam: 'Away Team',
      stade: 'Stadium',
      chose: 'Choose this match',
    },
    TripBookingStep: {
      offertitle: 'Choose an offer',
      simpletrip: 'Simple trip (bus only)',
      fulltrip: 'Full trip (bus and hotel)',
      billettitle: 'Choose ticket type',
      front: 'Front',
      turn: 'Turn',
      chosebus: 'Choose a bus',
      chosebusback: 'Choose a back bus',
      choseHotel: 'Choose an hotel',
      book: 'Book for ',
      errorTicket: 'You must choose a ticket type',
      errorTrip: 'You must choose a trip type',
      errorBus: 'You must choose a bus',
      errorBusBack: 'You must choose a backtrip bus',
      errorHotel: 'You must choose an hotel',
      retourOkay: 'You successfully booked this match',
    },
    BusBookingItem: {
      duree: 'duration',
    },
  },
  Fr: {
    Menubar: {
      Cal: "Calendrier",
      Eq: "Mon equipe",
      Res: "Reservation",
      Voy: "Mes voyages",
      Par: "Paramètres",
    },
    LoginButton: {
      co: 'Se connecter',
      disco: 'Se déconnecter',
    },
    Register: {
      bvn: 'Bienvenue sur Ovalion !',
      addr: 'Adresse email',
      mdp: 'Mot de passe',
      city: 'Ville',
      reg: 'S\'inscrire',
    },
    Login: {
      log: 'Se connecter',
      addr: 'Adresse email',
      mdp: 'Mot de passe',
    },
    Calendar: {
      allDay: 'journée',
      previous: 'précédent',
      next: 'suivant',
      today: 'aujourd\'hui',
      month: 'mois',
      week: 'semaine',
      day: 'jour',
      agenda: 'Agenda',
      date: 'date',
      time: 'heure',
      event: 'événement', // Or anything you want
      showMore: total => `+ ${total} événement(s) supplémentaire(s)`
    },
    Parametres: {
      title: 'Choisissez votre équipe',
      follow: 'Vous suivez',
      followAll: 'Suivre toutes les équipes',
      allteams: 'toutes les équipes',
      noFollow: 'Vous ne suivez aucune équipe',
    },
    MonEquipe: {
      rank: 'Classement',
      history: 'Historique des matchs',
      equipe: 'Equipe',
      noteam: 'Vous devez suivre une équipe avant d\'accéder à cette page',
      home: 'DOMICILE',
      away: 'EXTERIEUR',
    },
    MatchHistoryItem: {
      localeIdentifier: 'Fr',
    },
    Reserver: {
      choseMatch: 'Choisir un match',
      choseTrip: 'Choisir un voyage',
      payment: 'Paiement',
      home: 'DOMICILE',
      away: 'EXTERIEUR',
    },
    MatchBookingItem: {
      localeIdentifier: 'Fr',
      hometeam: 'Equipe à domicile',
      awayteam: 'Equipe à l\'extérieur',
      stade: 'Stade',
      chose: 'Choisir ce match',
    },
    TripBookingStep: {
      offertitle: 'Choisir une offre',
      simpletrip: 'Voyage simple (bus seulement)',
      fulltrip: 'Voyage complet (bus et hôtel)',
      billettitle: 'Choisir un type de billet',
      front: 'Tribune',
      turn: 'Virage',
      chosebus: 'Choisir un bus aller',
      chosebusback: 'Choisir un bus retour',
      choseHotel: 'Choisir un hôtel',
      book: 'Réserver pour ',
      errorTicket: 'Vous devez choisir un type de ticket',
      errorTrip: 'Vous devez choisir un type de voyage',
      errorBus: 'Vous devez choisir un bus aller',
      errorBusBack: 'Vous devez choisir un bus retour',
      errorHotel: 'Vous devez choisir un hôtel',
      retourOkay: 'La réservation s\'est déroulée avec succès',
    },
    BusBookingItem: {
      duree: 'durée',
    },
  }
};
